// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnoflgpywdoaefwtbcht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxub2ZsZ3B5d2RvYWVmd3RiY2h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTc4MDAsImV4cCI6MjA2MTA5MzgwMH0.UBpu9p2onfMhfTWrkWp-hFeMnhriJXUWeKmLWV9iOuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);